"""baseline schema — create all Osprey tables from model metadata

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-21

This baseline creates the full schema from ``SQLModel.metadata`` so a fresh
production database is provisioned by ``alembic upgrade head``. Subsequent schema
changes should be authored as normal autogenerated revisions.
"""

from __future__ import annotations

from collections.abc import Sequence

from sqlmodel import SQLModel

from alembic import op
from osprey import models  # noqa: F401  (register tables)

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    SQLModel.metadata.create_all(bind)


def downgrade() -> None:
    bind = op.get_bind()
    SQLModel.metadata.drop_all(bind)
