"""baseline schema — all Osprey tables

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-21

Explicit operations, autogenerated from the models against an empty Postgres, so the
schema is reviewable in the diff and the downgrade is granular. The revision id is
unchanged, so deployments that already applied the previous (create_all) form of this
revision will not re-run it; the resulting schema is identical, which the postgres CI
job verifies via an upgrade/downgrade round-trip plus ``alembic check``.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("prev_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["org.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_org_id"), "audit_log", ["org_id"], unique=False)
    op.create_table(
        "device",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("platform", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["org.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "token", name="uq_device_token"),
    )
    op.create_index(op.f("ix_device_org_id"), "device", ["org_id"], unique=False)
    op.create_index(op.f("ix_device_user_id"), "device", ["user_id"], unique=False)
    op.create_table(
        "membership",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sa.Enum("owner", "admin", "pm", "viewer", name="role"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["org.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "user_id", name="uq_membership"),
    )
    op.create_index(op.f("ix_membership_org_id"), "membership", ["org_id"], unique=False)
    op.create_index(op.f("ix_membership_user_id"), "membership", ["user_id"], unique=False)
    op.create_table(
        "project",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("weights", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["org.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_org_id"), "project", ["org_id"], unique=False)
    op.create_table(
        "ai_connection",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "provider", sa.Enum("claude", "openai", "ollama", name="aiprovider"), nullable=False
        ),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("encrypted_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "active", "degraded", "error", "revoked", name="connectionstatus"),
            nullable=False,
        ),
        sa.Column("last_used", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["org.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_connection_org_id"), "ai_connection", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_ai_connection_project_id"), "ai_connection", ["project_id"], unique=False
    )
    op.create_table(
        "connection",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("account_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("encrypted_tokens", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "active", "degraded", "error", "revoked", name="connectionstatus"),
            nullable=False,
        ),
        sa.Column("cursor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_sync", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["org.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_connection_org_id"), "connection", ["org_id"], unique=False)
    op.create_index(op.f("ix_connection_project_id"), "connection", ["project_id"], unique=False)
    op.create_table(
        "hotlist_snapshot",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("top_n", sa.Integer(), nullable=False),
        sa.Column("generated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hotlist_snapshot_project_id"), "hotlist_snapshot", ["project_id"], unique=False
    )
    op.create_table(
        "item",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "rfi",
                "change_order",
                "submittal",
                "invoice",
                "safety",
                "schedule",
                "contractual_notice",
                "general",
                name="category",
            ),
            nullable=False,
        ),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "snoozed", "dismissed", "done", name="itemstatus"),
            nullable=False,
        ),
        sa.Column("owner", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("snooze_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_project_id"), "item", ["project_id"], unique=False)
    op.create_table(
        "script_task",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("org_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("schedule_minutes", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("idle", "running", "ok", "error", "disabled", name="scriptstatus"),
            nullable=False,
        ),
        sa.Column("last_run", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_result", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["org.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_script_task_org_id"), "script_task", ["org_id"], unique=False)
    op.create_index(op.f("ix_script_task_project_id"), "script_task", ["project_id"], unique=False)
    op.create_table(
        "action",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("done", "snooze", "dismiss", "escalate", "assign", "reopen", name="actiontype"),
            nullable=False,
        ),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_action_item_id"), "action", ["item_id"], unique=False)
    op.create_index(op.f("ix_action_project_id"), "action", ["project_id"], unique=False)
    op.create_table(
        "score",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("urgency", sa.Float(), nullable=False),
        sa.Column("impact", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column(
            "bucket",
            sa.Enum("act_today", "this_week", "watch", "done", name="bucket"),
            nullable=False,
        ),
        sa.Column("factors", sa.JSON(), nullable=True),
        sa.Column("explanation", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_score_item_id"), "score", ["item_id"], unique=False)
    op.create_table(
        "signal",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("connection_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "source_kind",
            sa.Enum(
                "email",
                "rfi",
                "submittal",
                "change_order",
                "invoice",
                "task",
                "event",
                "doc",
                "observation",
                "general",
                name="sourcekind",
            ),
            nullable=False,
        ),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("thread_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("participants", sa.JSON(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.Column("item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connection_id", "external_id", name="uq_signal_dedupe"),
    )
    op.create_index(op.f("ix_signal_connection_id"), "signal", ["connection_id"], unique=False)
    op.create_index(op.f("ix_signal_external_id"), "signal", ["external_id"], unique=False)
    op.create_index(op.f("ix_signal_item_id"), "signal", ["item_id"], unique=False)
    op.create_index(op.f("ix_signal_project_id"), "signal", ["project_id"], unique=False)
    op.create_index(op.f("ix_signal_thread_key"), "signal", ["thread_key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signal_thread_key"), table_name="signal")
    op.drop_index(op.f("ix_signal_project_id"), table_name="signal")
    op.drop_index(op.f("ix_signal_item_id"), table_name="signal")
    op.drop_index(op.f("ix_signal_external_id"), table_name="signal")
    op.drop_index(op.f("ix_signal_connection_id"), table_name="signal")
    op.drop_table("signal")
    op.drop_index(op.f("ix_score_item_id"), table_name="score")
    op.drop_table("score")
    op.drop_index(op.f("ix_action_project_id"), table_name="action")
    op.drop_index(op.f("ix_action_item_id"), table_name="action")
    op.drop_table("action")
    op.drop_index(op.f("ix_script_task_project_id"), table_name="script_task")
    op.drop_index(op.f("ix_script_task_org_id"), table_name="script_task")
    op.drop_table("script_task")
    op.drop_index(op.f("ix_item_project_id"), table_name="item")
    op.drop_table("item")
    op.drop_index(op.f("ix_hotlist_snapshot_project_id"), table_name="hotlist_snapshot")
    op.drop_table("hotlist_snapshot")
    op.drop_index(op.f("ix_connection_project_id"), table_name="connection")
    op.drop_index(op.f("ix_connection_org_id"), table_name="connection")
    op.drop_table("connection")
    op.drop_index(op.f("ix_ai_connection_project_id"), table_name="ai_connection")
    op.drop_index(op.f("ix_ai_connection_org_id"), table_name="ai_connection")
    op.drop_table("ai_connection")
    op.drop_index(op.f("ix_project_org_id"), table_name="project")
    op.drop_table("project")
    op.drop_index(op.f("ix_membership_user_id"), table_name="membership")
    op.drop_index(op.f("ix_membership_org_id"), table_name="membership")
    op.drop_table("membership")
    op.drop_index(op.f("ix_device_user_id"), table_name="device")
    op.drop_index(op.f("ix_device_org_id"), table_name="device")
    op.drop_table("device")
    op.drop_index(op.f("ix_audit_log_org_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("org")
    # ### end Alembic commands ###

    # Postgres keeps ENUM types after their tables are dropped, so a
    # downgrade->upgrade round-trip would fail re-creating them. Autogenerate
    # does not emit these; drop them explicitly.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS actiontype")
        op.execute("DROP TYPE IF EXISTS aiprovider")
        op.execute("DROP TYPE IF EXISTS bucket")
        op.execute("DROP TYPE IF EXISTS category")
        op.execute("DROP TYPE IF EXISTS connectionstatus")
        op.execute("DROP TYPE IF EXISTS itemstatus")
        op.execute("DROP TYPE IF EXISTS role")
        op.execute("DROP TYPE IF EXISTS scriptstatus")
        op.execute("DROP TYPE IF EXISTS sourcekind")
